version: '4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sapi
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: leokntz/pratica4ac2:latest
    networks:
      - default
    environment:
      DB_HOST: database
    ports:
      - "8686:8080"
volumes:
  db-volume:
